version: "3"

vars:
  BREWFILE_PATH: os/mac/Brewfile

tasks:
  default:
    cmd: task -a

  zsh:
    cmd: stow zsh

  git:
    cmd: stow git

  tmux:
    cmd: stow tmux

  nvim:
    cmd: stow nvim

  ghostty:
    cmd: stow ghostty

  os:mac:brew:import:
    cmd: brew bundle --file {{.BREWFILE_PATH}} -f

  os:mac:brew:export:
    cmd: brew bundle dump --file {{.BREWFILE_PATH}} -f
