version: "3"

vars:
  BREWFILE_PATH: os/mac/Brewfile

tasks:
  default:
    cmd: task -a

  zsh:
    cmd: stow zsh

  git:
    cmd: stow git

  tmux:
    cmd: stow tmux

  nvim:
    cmd: stow nvim

  ghostty:
    cmd: stow ghostty
