version: "3"

vars:
  BREWFILE_PATH: os/mac/Brewfile

tasks:
  default:
    cmd: task -a

  git:
    cmd: stow git

  zsh:
    cmd: stow zsh

  os:mac:brew:import:
    cmd: brew bundle --file {{.BREWFILE_PATH}} -f

  os:mac:brew:export:
    cmd: brew bundle dump --file {{.BREWFILE_PATH}} -f
