version: "3"

vars:
  BREWFILE_PATH: os/mac/Brewfile

tasks:
  default:
    cmds:
      - task -a

  git:
    cmds:
      - stow git

  zsh:
    cmds:
      - stow zsh

  os:mac:brew:import:
    cmds:
      - brew bundle --file {{.BREWFILE_PATH}} -f

  os:mac:brew:export:
    cmds:
      - brew bundle dump --file {{.BREWFILE_PATH}} -f
